### ISSUE TITLE
Mesh doesn't load on the Vercel demo

### ISSUE THREAD

**Issue by corysimmons** [ektogamat/fake-glow-material-r3f#1]
![image](https://github.com/ektogamat/fake-glow-material-r3f/assets/224636/a7fb8091-70ab-435e-ad27-8d2a96c5e0ad)

No errors or anything in my console or Network tab.

Works on CodeSandbox though!

**Comment by ektogamat** [comment]
Ahh I'm sorry. I was just finishing the demo scene before publishing it ahah. I got me in the middle ;).

**Comment by corysimmons** [comment]
haha no worries! It's working now! Thanks again for the cool material! <3
