### ISSUE TITLE
Error: Can not resolve #include <colorspace_fragment>

### ISSUE THREAD

**Issue by nirtamir2** [ektogamat/fake-glow-material-r3f#3]
I run this FakeGlowMaterial and I get an error:
```
Error: Can not resolve #include <colorspace_fragment>
```

When I removed the 
```glsl
#include <tonemapping_fragment>
#include <colorspace_fragment>
```
lines - this worked.

**Comment by ektogamat** [comment]
Ahh okay. depending on the threejs version your project is running, you need to have different  includes. But removing them would not cause any damage. Thanks!
